### ISSUE TITLE
Calling renderJs() and renderStyles() in different template engines

### ISSUE THREAD

**Issue by victornswd** [Cowboy-coder/bundle-up#14]
Hi! I was wondering if you could help me out with this: 
I'm not using Jade in my projects (I'm using basic HTML combined with mustache) and I'm having problems calling `renderJs()` and `renderStyles`. I managed to trace the functions back to `app._locals.renderStyles()` and `app._locals.renderJs()` but I have no idea how to call them in my templates.

If you have any suggestions, I would love to hear them out!

Thanks!

**Comment by victornswd** [comment]
Never mind, I found the solution to this problem, i just had to drop the parens (eg: `renderJs()` -> `renderJs`) when calling the functions unescaped.

**Comment by Cowboy-coder** [comment]
Ah, cool!
