### ISSUE TITLE
Plans for supporting express 3

### ISSUE THREAD

**Issue by adiospace** [Cowboy-coder/bundle-up#15]
Hi I'm using BundleUp with express 3 alpha and is working fine if instead of @app.helpers, the new @app.locals is used. Do you have any plans of supporting express 3? Maybe a new tag?

**Comment by Cowboy-coder** [comment]
It's annoying to support two separate versions just because of an api change in Express 3.X. Preferably I want to support both versions(2.x and 3.x) of Express using the same code base. I'll look into it!

**Comment by Cowboy-coder** [comment]
This should work both in 2.X and 3.X https://github.com/Cowboy-coder/bundle-up/commit/a18e13dfbdd8b4c43017f8b322c70e5e42047680
