### ISSUE TITLE
Node 0.8.0 support

### ISSUE THREAD

**Issue by peters** [Cowboy-coder/bundle-up#19]
Is there any plans for support node 0.8.0 ?

**Comment by Cowboy-coder** [comment]
Of course. I just need to check all tests and stuffs for 0.8.0 first.

**Comment by peters** [comment]
Great! :)

**Comment by Cowboy-coder** [comment]
All tests passed in 0.6 and 0.8. I only changed engine in `package.json` to support 0.8. New release in npm

**Comment by peters** [comment]
Ty for quick feedback :)
