### ISSUE TITLE
Bug when running multiple node.js processes

### ISSUE THREAD

**Issue by blindsey** [Cowboy-coder/bundle-up#20]
When running with multiple node.js processes (distribute/up), the generated files become mangled if the same request comes in at the same time. I believe this is caused by the compiler writing to the same file from multiple sources.

**Comment by Cowboy-coder** [comment]
I think that 79416506cec054a8f37eed9231a4c44e406ace25 and 10c9d9510e92be1c10e694d190677d4d044dbcae  should solve your issue. The tests seems a bit shaky on 0.8 for this though.
