### ISSUE TITLE
TypeError caused by upgraded version of uglify.js

### ISSUE THREAD

**Issue by meetamit** [Cowboy-coder/bundle-up#26]
Howdy,

Version 2.x of uglify is out, and npm ends up picking up this new version – since Bundle-Up's package.json specifies "uglify-js": ">= 1.2.5" .

This latest uglify version has a new API/structure, and as a result BundleUp errors:

TypeError: Cannot call method 'parse' of undefined
    at Js.minify (/app/node_modules/bundle-up/lib/js.coffee:25:29)

The simplest fix (which I've verified works on my machine) is to change Bundle-Up's package.json to specify "uglify-js": "< 2.0"

**Comment by meetamit** [comment]
Off course an even quicker fix is to turn off minification:

BundleUp(app, __dirname + '/lib/assets', {
  staticRoot: __dirname + '/public/',
  staticUrlRoot:'/',
  bundle: true,
  minifyCss: false,// <-- THIS
  minifyJs: false// <-- AND THIS
});

**Comment by Cowboy-coder** [comment]
I will take a look at this in a couple of days. I do ofc. accept pull requests. I want to support the new interface in 2.x and not make a `"uglify-js":"< 2.0"`-fix though.

**Comment by meetamit** [comment]
Hey, thanks for getting back....
I'll happily work on the integration with uglify 2.x. It'll take me too a few days to get to it, and it would be my first pull request (so you might have to bear w/ me a bit), but it would be a good exercise for me to go though.
Will get in touch as soon as I have something.
Cheers.

**Comment by Pyppe** [comment]
+1

**Comment by Cowboy-coder** [comment]
New version in npm!
