### ISSUE TITLE
When bundle, minifyCss & minifyJs all true, Bundle-Up may cause 1st request to fail

### ISSUE THREAD

**Issue by gdibble** [Cowboy-coder/bundle-up#28]
```
bundleUp(app, __dirname + '/assets', {
    staticRoot: __dirname + '/public/',
    staticUrlRoot: '/',
    bundle:    true,
    minifyCss: true,
    minifyJs:  true
  });
```
1. Start server: node server
2. Browser req 1: total bundling & minifications may take too long for some browsers
3. Browser req 2: html/css/js returned (in-time) and app loads/works fine

**In IE**, the request timeout appears to be longer and the app always loads
**In Chrome, Firefox, Opera & Safari**, the request timeout seems to be shorter and they usually show the 404 response pg/msg

[It appears that everything works fine on the 1st req. (i.e. Bundle-Up does its job), only that these browsers give up on the request because it took too long.]

In assets.js, I am bundling:
- 8 CSS files (most already minified) which result in a 122KB bundled+minified stylesheet
- 23 JS files (most already minified), which result in a 426KB bundled+minified script

![bundle-up-bug-report---slow-response-may-404-browser](https://f.cloud.github.com/assets/906846/15361/fedbc56a-4747-11e2-8ca6-fb46082a8b21.png)

_Would streaming content help?_

_Thoughts? Ideas?_

**Thank you :)**

**Comment by Cowboy-coder** [comment]
The reason is because when `bundle:true` is enabled the "bundling" of all the js and css files will happen synchronously. This is to prevent the server from starting before the bundled files has been prepared. Otherwise the first request runs a risk of returning broken css and/or javascript.

**Comment by gdibble** [comment]
Thank you for the quick response! That makes sense. I was thinking of trying different ideas like namespacing, but based on your response, if anything that would only add milliseconds to the total response time. If there is anything I can do to help [feedback / test / etcetera], I certainly will - _cheers for an awesome module_ :beers:

**Comment by Cowboy-coder** [comment]
I need help with Windows issues if you are up for it. As long as the tests passes feel free to submit a pull request :)

**Comment by gdibble** [comment]
Wait, this issue should not be closed because it's still happening and there is no reasonable workaround (besides disabling core functionality), solution or patch as of yet. Let's please not sweep this under the rug.
Would your idea be to remove CSS/JS files from the assets.js or simply criple functionality (by disabling UglifyJS thus js.min?)
Have you tried bundling and minifying CSS as one asynchronous process and JS as another, such that they could run in parallel and then once both results are obtained, include and finally start the server? I'm just thinking about different ideas to speed up both operations (possibly at once), and I'm curious what you've tested.

## 

[*btw: I have dev environments that are windoze, but prod is usually linux/cloud. Let me know how I can help :: thanks]

**Comment by Cowboy-coder** [comment]
But the issue is only related to startup speed right? So I closed this one because there's already a ticket about improving startup speed here https://github.com/Cowboy-coder/bundle-up/issues/23

**Comment by gdibble** [comment]
nod > I see that now :) yes, let's use #23 as it was opened sooner and will keep issues more manageable
