### ISSUE TITLE
Add minfiication of javascript

### ISSUE THREAD

**Issue by Cowboy-coder** [Cowboy-coder/bundle-up#3]
using UglifyJS https://github.com/mishoo/UglifyJS.

Make it together with minfiication of css configurable.

Should minification be default?

**Comment by panosru** [comment]
on the pull request I just send I just used your already existed method `minify` and added the support but I believe it shouldn't be by default, as I saw your code is well abstracted so `bundle.coffee` there where you call the `minify` method you could hook a statement where you would check if the minification should be processed or not

**Comment by Cowboy-coder** [comment]
Yeah, I think I agree with you that minification shouldn't be default.
