### ISSUE TITLE
bundle-up2/lib/bundle_up.coffee, Cannot call method 'find' of undefined

### ISSUE THREAD

**Issue by rukamart** [Cowboy-coder/bundle-up#30]
hi
I use bundle-up2@0.4.5 whitch node 0.10.0 and my program have an error:

[TypeError: In /home/rui/workspace/master/node_modules/bundle-up2/lib/bundle_up.coffee, Cannot call method 'find' of undefined]
TypeError: In /home/rui/workspace/master/node_modules/bundle-up2/lib/bundle_up.coffee, Cannot call method 'find' of undefined

if anyone can help me I appreciate

**Comment by Cowboy-coder** [comment]
bundle-up2 is a fork of this repo so you'll need to move your issue to this repo instead https://github.com/FGRibreau/bundle-up
