### ISSUE TITLE
best way of using nib with bundle-up?

### ISSUE THREAD

**Issue by panosru** [Cowboy-coder/bundle-up#9]
Hi, sorry for posting too many issues in one day... I have a question, since you mentioned nib, how should I use it ?

With bundle-up I removed `app.use(stylus.middleware({...` from my express application since I don't need it any more, I have everything bundled so I don't need stylus middleware to generate any css for me on request, bundle-up have it covered already...  I could use of course a pre minify hook on css if we had this feature but till then, how you suggest me to use nib with bundle-up?

**Comment by Cowboy-coder** [comment]
Yeah, it's an un-documented feature, but you can provide custom compilers like this 

``` js
BundleUp(app, 'assets.js', {
  bundle: true,
  staticRoot: __dirname + '/public',
  staticUrlRoot: '/',
  compilers: {
    stylus: function(str, path) {
      return stylus(str)
      .set("filename", path)
      .set("compress", true)
      .use(nib())
      .import("nib") // This imports the nib lib
    }
  }
}
```

I will add a better readme/documentation after the refactoring of the API.

**Comment by panosru** [comment]
Thanks for the reply! :) I will try it ;)
